version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev_database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc123456789
      POSTGRES_DB: tmdtdb
    networks:
      - nestjs-network
networks:
  nestjs-network: 
  # docker compose up -d: create container
  # docker ps: list docker
  # docker start name_container

